apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    {{- include "k8s-daily-monitor.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}{{ .Values.backend.service.type }}{{ end }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
      {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.backend }}
      {{- end }}
  selector:
    app.kubernetes.io/name: backend
