apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: ui
    {{- include "k8s-daily-monitor.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}{{ .Values.frontend.service.type }}{{ end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.frontend }}
      {{- end }}
  selector:
    app.kubernetes.io/name: frontend
