apiVersion: v1
kind: Secret
metadata:
  name: k8s-monitor-secret
  labels:
    {{- include "k8s-daily-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USER: {{ .Values.secrets.databaseUser | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ include "k8s-daily-monitor.databaseUrl" . | quote }}
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
